### ISSUE TITLE
Auto rotate seems to be not working on iphone

### ISSUE THREAD

**Issue by varunbhayami** [prateekrastogi/videojs-landscape-fullscreen#16]
Dear developer, 

I am using this library in react.js, below is my code i have implemented.
`this.player.landscapeFullscreen({
                fullscreen: {
                    enterOnRotate: true,
                    alwaysInLandscapeMode: true,
                    iOS: true
                }
            })`

Above code seems to be not working on iPhone browser(Chrome-safari),
When I tilt the screen to the landscape video doesn't play in fullscreen.
On android, video goes to the full screen but it doesn't get back in portrait when I tilt the phone to the portrait mode.

Any help will be appreciated.
Thanks in advance.

**Comment by prateekrastogi** [comment]
Buy new Samsung S20+
