### ISSUE TITLE
Android, from landscape to portrait close fullscreen

### ISSUE THREAD

**Issue by LudovicoPiccolo** [prateekrastogi/videojs-landscape-fullscreen#22]
Hi,

when I turn the phone from portrait to landscape , the video becomes fullscreen.

Is it possible that if I turn the phone from landscape to portrait it returns to normal?

Try here: http://www.ludosweb.net/player/

Thanks

**Comment by prateekrastogi** [comment]
Yes it does exactly that

**Comment by LudovicoPiccolo** [comment]
It doesn't work on android, can you help me understand where am I wrong?

I don't have ios to try

Thanks

**Comment by prateekrastogi** [comment]
@LudovicoPiccolo  It now works perfectly. There was bug in Chrome in few days earlier release. Kindly update your mobile browser. I am on S20+ Chrome.
