### ISSUE TITLE
Error when refreshing page on Nuxt.js

### ISSUE THREAD

**Issue by ceferrari** [prateekrastogi/videojs-landscape-fullscreen#26]
I am getting the following error whenever I refresh the page:

`Cannot set property 'lockOrientationUniversal' of undefined`

Nuxt.js, Chrome, Windows.

Is it really needed to set the `lockOrientationUniversal` on the `screen` const instead of a local Javascript function?

`const lockOrientationUniversal = function(mode) ...`

Even after manually fixing it for testing purposes on my local files, I get a second error, about `fetch` not being defined.

**Comment by prateekrastogi** [comment]
You just have to render videojs on client without SSR to make it work on browser environment.

**Comment by smohammadhn** [comment]
even wrapping my component in `<client-only>` tag didn't fix the issue.
