### ISSUE TITLE
Question about the orientation logic for Android and iOS

### ISSUE THREAD

**Issue by ceferrari** [prateekrastogi/videojs-landscape-fullscreen#27]
Is the logic below correct?
- https://github.com/prateekrastogi/videojs-landscape-fullscreen/blob/master/src/plugin.js#L21-L28

Both IFs return the same value, which doesn't make sense to me. Shouldn`t the second IF return the following?:
- `screen.orientation.angle`

**Comment by prateekrastogi** [comment]
It's mere typecast of angle, and both if are necessary.

**Comment by ceferrari** [comment]
Typecast? I can't see any in the lines I highlighted.

Anyway, as soon as I changed the return of the second IF to `return screen.orientation.angle` it started working for me on Chrome + DevTools simulating an Android device, which doesn`t work with the original code.

**Comment by prateekrastogi** [comment]
great to proposed change was working for you `dev tools`
