### ISSUE TITLE
exitOnRotate doesn't work on Android

### ISSUE THREAD

**Issue by tolew1** [prateekrastogi/videojs-landscape-fullscreen#28]
I have tried to use this with the latest version, and it doesn't go back portrait when you rotate it back. 

I tried this and does not work. 
```
fullscreen: {
                enterOnRotate: true,
                exitOnRotate: true,
                alwaysInLandscapeMode: false,
                iOS: true
              }
```

Nothing I've tried will work. I'm using Android 12 - Chrome v100

**Comment by prateekrastogi** [comment]
///GSM

kindly retry with latest version of chromium.
