### ISSUE TITLE
Why are we fetching the package from CDN here?

### ISSUE THREAD

**Issue by KVPasupuleti** [prateekrastogi/videojs-landscape-fullscreen#30]
https://github.com/prateekrastogi/videojs-landscape-fullscreen/blob/5b5232f0e20112455e9121a10efb1e983fadcff5/src/plugin.js#L128

In the above line, why are we fetching the package from CDN here?

I suppose the plugin itself is enough. 

Is there any specific purpose for this line which this plugin file lacks?

@prateekrastogi

**Comment by prateekrastogi** [comment]
We're here executing asynchronous javascript GraphQL optimization of ECMAScript, on promise, to increase performance latency.

It will make PRPL, MVC, MVVM, on webgl.

**Comment by SimonZhangITer** [comment]
fetch error
