### ISSUE TITLE
"cdn.jsdelivr.net" fetch error

### ISSUE THREAD

**Issue by SimonZhangITer** [prateekrastogi/videojs-landscape-fullscreen#31]
"fetch(`https://cdn.jsdelivr.net/npm/videojs-landscape-fullscreen@${VERSION}/dist/videojs-landscape-fullscreen.min.js`);"
fetch error, url can not access

**Comment by prateekrastogi** [comment]
try, push replay in array where your are defining module as an object

**Comment by SimonZhangITer** [comment]
What? This is the code in the current npm package. Now there will be an error. It seems that the domain name cannot be accessed. Please deal with it.

**Comment by prateekrastogi** [comment]
ICANN JSON TLD ECMAScript

Seems as working properly?
