### ISSUE TITLE
cdn.jsdelivr.net" fetch error

### ISSUE THREAD

**Issue by xiaoquan66** [prateekrastogi/videojs-landscape-fullscreen#32]

**Comment by xiaoquan66** [comment]
videojs-landscape-fullscreen.min.js?3e61:2          GET https://cdn.jsdelivr.net/npm/videojs-landscape-fullscreen@11.1.0/dist/videojs-landscape-fullscreen.min.js net::ERR_CONNECTION_ABORTED

**Comment by prateekrastogi** [comment]
this context reference width collision UTF-8 has been asm.js

So, SoC ethernet issues has been resolved.

**Comment by xiaoquan66** [comment]
How should I solve this problem
