### ISSUE TITLE
Stoped working for Android.

### ISSUE THREAD

**Issue by onigetoc** [prateekrastogi/videojs-landscape-fullscreen#34]
I created a web app as a WPA where you can install a free IPTV player and list at first the landscape worked but stopped some weeks/months ago on Android. I do not know if google change something or what.  
Event the fullscreen button stopped working to.

video IPTV web app website: https://hlsiptv.com/

I used: 

```
const player = videojs('vid1', 'options');

   player.landscapeFullscreen();
```

**Comment by onigetoc** [comment]
Ok, they just changed the manifest.json display fullscreen to standalone.
fullscreen worked before for fullscreen video but not now.

**Comment by prateekrastogi** [comment]
It works in Android, exactly the same way as iOS.
