### ISSUE TITLE
o.orientation.lock is not a function. (In 'o.orientation.lock(e)', 'o.orientation.lock' is undefined)

### ISSUE THREAD

**Issue by dalalRohit** [prateekrastogi/videojs-landscape-fullscreen#35]
I have been getting this error a lot on Sentry for the last few weeks.
This only happens on iPhones & iPads. 

Attaching a screenshot as well.

![image](https://github.com/prateekrastogi/videojs-landscape-fullscreen/assets/32014253/6a60d3d2-0d3b-4967-9ebc-d92020127829)

Any help is highly appreciated  😄 
Thank you 🙌🏻

**Comment by prateekrastogi** [comment]
please run it in pure browser environment

**Comment by LavanyaBurlagadda** [comment]
@prateekrastogi 

I am also facing the same issue in latest versions of IOS above 16.4, I am running the video in a safari browser.

**Comment by prateekrastogi** [comment]
@LavanyaBurlagadda Please refer this issue https://github.com/prateekrastogi/videojs-landscape-fullscreen/issues/36
