### ISSUE TITLE
Can't exit fullscreen mode on Android

### ISSUE THREAD

**Issue by VLADOS776** [prateekrastogi/videojs-landscape-fullscreen#4]
Hi,

When I rotate the phone into landscape mode video enters into the fullscreen mode.
But nothing happens when I rotate it back to the portrait mode.
Video stays in the landscape & fullscreen modes. It only rotates by the 180 degrees.

Looks like the `orientationchange` event is not triggering.
But on Youtube it works somehow.

**Comment by prateekrastogi** [comment]
Please use android remote debugging to share detailed debug information specific to your browser as its working on my android device perfectly. 

Will mark the issue as stale after one week, if you are not interested.

**Comment by prateekrastogi** [comment]
Closing this issue. Please consider detailing user-agent specific debug info for such issues.
